### ISSUE TITLE
Question about openstack-ansible

### ISSUE THREAD

**Issue by ksingh7** [openstack-ansible/openstack-ansible#34]
Hello Developers 

Excuse me i didn't find a good place to post this question , so putting it here. You can provide me the answer and close this issue.

1#  Is this module only valid for Ubuntu. Can i deploy openstack using this ansible module on CentOS machines. 

2#  What version of openstack does it deploy , Havana / ICH / J / K ?  where file / variable i need to update if i want to change openstack version ?

**Comment by lorin** [comment]
This repo isn't being actively maintained anymore. I suggest you check out https://github.com/stackforge/os-ansible-deployment as an alternative.
