### ISSUE TITLE
Enable docker engine as a virtualization

### ISSUE THREAD

**Issue by aabdulwahed** [openstack-ansible/openstack-ansible#38]
Dear All,

I would like if your ansible scripts support docker containers that can be provisioned using OpenStack.

If not please add it to your RODO it or I can push mine 

Thanks in advance 
Ahmed Abdullah

**Comment by lorin** [comment]
We aren't currently doing active development on this repo. You might want to check with the [official OpenStack-Ansible project](https://github.com/openstack/openstack-ansible) instead.
