### ISSUE TITLE
Problem creating a temporary directory

### ISSUE THREAD

**Issue by josanabr** [openstack-ansible/openstack-ansible#5]
After vms creation and when an ubuntu repository was about to be added the following message appeared:

TASK: [ensure add-apt-repository, ubuntu-cloud-keyring and ntp are present] **\* 
The authenticity of host '192.168.206.131 (192.168.206.131)' can't be established.
ECDSA key fingerprint is 11:5d:55:29:8a:77:d8:08:b4:00:9b:a3:61:93:fe:e5.
Are you sure you want to continue connecting (yes/no)? yes
fatal: [192.168.206.131] => could not create temporary directory, SSH (mkdir -p $HOME/.ansible/tmp/ansible-1375404585.58-16393091086278 && chmod a+rx $HOME/.ansible/tmp/ansible-1375404585.58-16393091086278 && echo $HOME/.ansible/tmp/ansible-1375404585.58-16393091086278) exited with result 255
fatal: [192.168.206.130] => could not create temporary directory, SSH (mkdir -p $HOME/.ansible/tmp/ansible-1375404585.58-10499516672503 && chmod a+rx $HOME/.ansible/tmp/ansible-1375404585.58-10499516672503 && echo $HOME/.ansible/tmp/ansible-1375404585.58-10499516672503) exited with result 255

FATAL: all hosts have already failed -- aborting

PLAY RECAP *******************************************************************\* 
           to retry, use: --limit @/var/tmp/ansible/openstack.yaml.retry

192.168.206.130            : ok=0    changed=0    unreachable=1    failed=0  
192.168.206.131            : ok=0    changed=0    unreachable=1    failed=0

**Comment by saikiran9392** [comment]
I have the same issue
could not make dir
